/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef CPPHELLO_H
#define CPPHELLO_H

#ifdef _WIN32
#define CPPHELLO_EXPORT_FUNC __declspec(dllexport)
#else
#define CPPHELLO_EXPORT_FUNC
#endif

#include <string>

namespace cpphello {
    class Greeter {
        public:
        std::string CPPHELLO_EXPORT_FUNC greeting();
    };
}

#endif
